buildscript {
    ext {
        cleanArchitectureVersion = '3.26.1'
        springBootVersion = '3.5.4'
        sonarVersion = '6.3.1.5724'
        jacocoVersion = '0.8.13'
        pitestVersion = '1.19.0-rc.1'
        lombokVersion = '1.18.38'
    }
}

plugins {
    id 'co.com.bancolombia.cleanArchitecture' version "${cleanArchitectureVersion}"
    id 'org.springframework.boot' version "${springBootVersion}" apply false
    id 'info.solidsoft.pitest' version "${pitestVersion}" apply false
    id 'org.sonarqube' version "${sonarVersion}"
    id 'jacoco'
}

sonar {
    properties {
        property "sonar.host.url", "http://localhost:9000"  // URL del servidor SonarQube
        property "sonar.token", System.getenv('SONAR_TOKEN') ?: project.findProperty('sonarToken')
        // Token de autenticación
        property "sonar.projectKey", "ms-person-v1"     // Clave única del proyecto
        property "sonar.projectName", "MS Person V1"    // Nombre del proyecto
        property "sonar.sourceEncoding", "UTF-8"
        property "sonar.java.binaries", "**/build/classes/java/main"
        property "sonar.junit.reportsPath", "**/build/test-results/test"
        property "sonar.java.coveragePlugin", "jacoco"
        property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacocoMergedReport/jacocoMergedReport.xml"
        property "sonar.test.inclusions", "**/*Test.java"
        property "sonar.exclusions", "**/MainApplication.java"
    }
}

apply from: './main.gradle'
