package=co.com.pragma
systemProp.version=3.26.1
reactive=true
lombok=true
metrics=true
language=java
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.integrity-check=true
systemProp.sonar.gradle.skipCompile=true
# Configuración SonarQube
systemProp.sonar.host.url=http://localhost:9000
sonarToken=squ_8a9149e7fbf79e7be752c504a88c742a738fa22b
